export const NOTIFICATION_CONFIG = {
  DEFAULT_ETA_ALERT_THRESHOLD_MINUTES: 10,
  DEFAULT_STOP_ARRIVAL_RADIUS_METERS: 50.0,
  STOP_DEPARTURE_BUFFER_METERS: 30.0,
  MAX_ARRIVAL_GPS_ACCURACY_METERS: 50.0,
  MAX_GPS_AGE_FOR_ARRIVAL_SECONDS: 120,
  CONSECUTIVE_PINGS_FOR_ARRIVAL: 2,
  MAX_RETRY_ATTEMPTS: 3,
  INITIAL_RETRY_BACKOFF_MS: 500,
  BACKOFF_MULTIPLIER: 2,
  MAX_PAGINATION_LIMIT: 100,
  DEFAULT_PAGINATION_LIMIT: 20,
  MAX_DEVICE_TOKEN_LENGTH: 1024,
  SSE_HEARTBEAT_INTERVAL_MS: 15000,
} as const;

export const NOTIFICATION_CHANNELS = {
  FCM: 'FCM',
  IN_APP: 'IN_APP',
} as const;
